Use JSON to load options for reason for removal
* Pair up JSON with respective `*Modals.html` in includes folder... seems to be the optimum place

**NOTE**:

*mu2* still has a bug where it throws an error if `option` tag doesn't have a close

``` sh-session
mu2/lib/mu/parser.js:158
        throw new Error("Unclosed section " + name);
              ^
Error: Unclosed section modTools.removeReasons
```

... so in short close the tag to avert it.

Closes #261