Some dep updates
* Please read their CHANGELOGs ... and there is a lot
* Delete op retested

NOTES:
* *async*@3.x may not support IE11 well... needs further testing... failure on dev script source in Chromium 73.0.3683.86 and quite sluggish on dev
* Further *kerberos* failures... no updates yet:

``` console
~/.node-gyp/12.3.0/include/node/node.h:107:12: fatal error: util-inl.h: No such file or directory
```

... ignoring for now since it's still a very highly optional dep:

* https://stackoverflow.com/questions/40432272/cannot-open-include-file-src-gtest-internal-inl-h-no-such-file-or-directory (some solution but seems to be *node* related)